### PR TITLE
Correct CWD

### PR DESCRIPTION
**Pull request by jrarmstro**
11-sysop.cgi and 11-dragon.cgi boldly that 11-config.pl will be located in the current working directory, which is not always the case:
`require "11-config.pl";`

This results in errors when the CWD is not the same as the 11-sysop.cgi file location:
`Can't locate 11-config.pl in @INC (@INC contains: C:/Strawberry/perl/site/lib C:/Strawberry/perl/vendor/lib C:/Strawberry/perl/lib) at C:/[omitted]/DragonBasher/cgi-bin/11-dragon/11-sysop.cgi line 15.`

This solves that issue by adding the parent directory of these files to the @INC.

### CODE REVIEW

**Comment by Quasic** [comment]
Thanks for the PR. I'm not sure if adding to @INC should be done by default, but it should probably be an option, if the cgi system might not set up the CWD as we assume...

**Comment by jrarmstro** [comment]
I finally managed to make Apache add the directory to @inc, and closed this issue. Definitely worth keeping in mind though

**Comment by jrarmstro** [comment]
From my reading the general consensus seemed to be that you should never assume the CWD will be correct, although we may cut corners in this case for performance reasons

**Comment by Quasic** [comment]
We probably don't need to worry so much about performance in 11-sysop.cgi. If we can detect the problem, there, we could issue a helpful error message, maybe applying your fix, or leave that as an option the user can select to continue setup...

**Comment by Quasic** [comment]
Joe would prefer we either change CWD or use $cgidir to prefix all .pl scripts, like we do for other paths.

I'm thinking that if we just remove all text after the last slash (backslash may need detecting on windows) we wouldn't need a module to set the variable, but I'd like to see how the module does it...

EDIT: the last slash should also be removed, so we can use it like "$cgidir/config.pl"

**Comment by jrarmstro** [comment]
Simply adding the CWD to @inc should cover a lot of cases too, since it seems CWD is not included in @inc by default by some interpreters etc.

(untested)
`use lib '.';`

You can also do a lot of manipulation based on $0 etc

**Comment by Quasic** [comment]
man lib says the module is kept small, and the path is placed at the first-searched position, so performance shouldn't be a problem for the actual includes, if used after any other modules.

```Perl
use lib "/unix/path";
```
as well as direct setting of @INC might be tricky with some systems, but
```Perl
use lib '.';
```
or just modifying @INC directly if '.' isn't found in the right position, might work until we have a good way to get a unix path to the parent folder.

**Comment by Quasic** [comment]
I just tried a test in one setup, and lib moved '.' from the end to the start of `@INC`, which I expect would actually improve performance.

**Comment by Quasic** [comment]
I don't think we need to worry about memleaks with one possible duplication in the list, and no more libraries are loaded after this, anyway, so I left out that part of what lib.pm does. We could just replace the list with the one path, but I didn't want to impose that limit, here, just in case...

**Comment by Quasic** [comment]
I was going to add it to 11-dragon.cgi after it was working in 11-sysop.cgi, but I think I'll move it over, now, and fix another issue, while I'm at it.

**Pull request closed without merging**
